[package]
name = "steel-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0.107"
quote.workspace = true
proc-macro2.workspace = true

[lints]
workspace = true
