[package]
name = "steel-registry"
version.workspace = true
edition.workspace = true
build = "build/build.rs"

[dependencies]
steel-utils = { path = "../steel-utils" }
serde_json.workspace = true
serde.workspace = true
rustc-hash.workspace = true
log.workspace = true


[build-dependencies]
proc-macro2.workspace = true
quote.workspace = true
serde_json.workspace = true
serde.workspace = true
steel-utils = { path = "../steel-utils" }
heck = "0.5.0"
rustc-hash.workspace = true

[features]
fmt = []
