[build]
rustflags = ["-Zthreads=8", "-Ctarget-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=lld"]
