[package]
name = "steel-utils"
version.workspace = true
edition.workspace = true
build = "build/build.rs"


[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
num-traits = "0.2.19"
simdnbt.workspace = true
uuid.workspace = true
phf = { version = "0.13.1", features = ["macros"] }
md5 = "0.8.0"
enum_dispatch.workspace = true
log.workspace = true
wincode.workspace = true
rustc-hash.workspace = true
parking_lot.workspace = true

[dev-dependencies]
criterion = "0.7"

[build-dependencies]
heck = "0.5.0"
proc-macro2.workspace = true
quote.workspace = true
serde_json.workspace = true
phf_codegen = "0.13.1"
rustc-hash.workspace = true

[[bench]]
name = "xoroshiro"
harness = false

[[bench]]
name = "legacy_random"
harness = false

[lints]
workspace = true
