[package]
name = "steel-utils"
version.workspace = true
edition.workspace = true
build = "build/build.rs"

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
num-traits = "0.2.19"
simdnbt.workspace = true
uuid.workspace = true
phf = { version = "0.13.1", features = ["macros"] }
log.workspace = true

[build-dependencies]
heck = "0.5.0"
proc-macro2.workspace = true
quote.workspace = true
serde_json.workspace = true
phf_codegen = "0.13.1"
