[package]
name = "steel"
version.workspace = true
edition.workspace = true


[dependencies]
steel-utils = { path = "../steel-utils" }
steel-core = { path = "../steel-core" }
steel-registry = { path = "../steel-registry" }
steel-protocol = { path = "../steel-protocol" }
tokio.workspace = true
scc.workspace = true
tokio-util.workspace = true
crossbeam.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
thiserror.workspace = true
log.workspace = true
simplelog = "0.12.2"
sha2 = "0.10.9"
sha1 = "0.10.6"
reqwest.workspace = true
rand.workspace = true
rsa.workspace = true
rsa-der = "0.3.0"
hex = "0.4.3"
parking_lot = { workspace = true, features = [
    "deadlock_detection",
], optional = true }

[lints]
workspace = true


[features]
deadlock_detection = ["dep:parking_lot"]
