[package]
name = "steel"
version.workspace = true
edition.workspace = true


[dependencies]
steel-utils = { path = "../steel-utils" }
steel-world = { path = "../steel-world" }
steel-registry = { path = "../steel-registry" }
steel-protocol = { path = "../steel-protocol" }
tokio.workspace = true
scc.workspace = true
bytes.workspace = true
tokio-util.workspace = true
crossbeam.workspace = true
serde.workspace = true
uuid.workspace = true
thiserror.workspace = true
log.workspace = true
simplelog = "0.12.2"
serde_json5 = "0.2.1"
base64 = "0.22.1"
rsa = "0.10.0-rc.9"
rsa-der = "0.3.0"
rand = "0.9.2"
sha2 = "0.10.9"
