[package]
name = "steel"
version.workspace = true
edition.workspace = true


[dependencies]
steel-utils = { path = "../steel-utils" }
steel-core = { path = "../steel-core" }
steel-registry = { path = "../steel-registry" }
steel-protocol = { path = "../steel-protocol" }
tokio.workspace = true
scc.workspace = true
tokio-util.workspace = true
crossbeam.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
thiserror.workspace = true
log.workspace = true
simplelog = "0.12.2"
sha2 = "0.10.9"
sha1 = "0.10.6"
reqwest = { version = "0.12.24", features = [
    "json",
    "rustls-tls",
], default-features = false }
rand = "0.9.2"
rsa = "0.10.0-rc.9"
rsa-der = "0.3.0"
hex = "0.4.3"
